### PR TITLE
adjust tree models below plane

### PR DESCRIPTION
**Pull request by TumeniNodes**
Try these out.
Tree 2 did not even appear, there seems to not be enough data in that file?

### CODE REVIEW

**Comment by MrChiantos** [comment]
I go look reason for tree and test for other trees.

**Comment by TumeniNodes** [comment]
uh, you should have checked them out first to see if there still exist some issues.
But we can work with this if there are

**Comment by MrChiantos** [comment]
I have Actually same problem.

**Comment by MrChiantos** [comment]
For tree2, i have see you have partial files

**Comment by MrChiantos** [comment]
@TumeniNodes

**Comment by MrChiantos** [comment]
For tree2, i have see you have partial files @TumeniNodes for unknown reason.

**Comment by TumeniNodes** [comment]
tree2 did not even show in Blender. The file size is very small, indicating there is a problem with that .obj file. That is the file which was in your original repo.

My repo, is just a fork of your own. Check the source you got that file from to see if it is correct

**Pull request merged**
